services:
    app:
        container_name: docsmith
        build:
            context: .
        env_file: .env
        environment:
            POPPLER_BINARY_PATH: /usr/bin/
            UNRTF_BINARY_PATH: /usr/bin/
        ports:
            - 127.0.0.1:${SERVICE_PORT:-8204}:${SERVICE_PORT:-8204}
